In [1]:
import matplotlib.pyplot as plt

import  torch.utils.data as data_utils
import torch
import torch.nn as nn
from torchvision.models import inception
from torchvision.models import Inception3
import numpy as np
from torch.autograd import Variable
import torch.nn.functional as F

from torchvision import datasets,models,transforms
import torch.optim as optim


import numpy as np
import random
import gc

import copy
import torch
import numpy as np
from torch.autograd import Variable
import sys
import os
import scipy
import cv2
from PIL import Image
from nndev import model_pip

In [ ]:
res_tf = models.resnet18(pretrained=True)
alex_tf = models.alexnet(pretrained=True)

In [ ]:
res_new = models.resnet18(pretrained=False)
alex_new = models.alexnet(pretrained=False)

In [2]:
res = models.resnet18(pretrained=True)
res.fc = nn.Linear(res.fc.in_features,15)

In [6]:

obj = model_pip(res,scale=True,batch_size=30,epochs=1,use_gpu=False)


In [7]:
model = obj.train_model()
#a,b,c = obj.transform()

{'train': 90, 'val': 240}
Epoch =  0
lr =  0.001
traintrain Loss: 0.0950 Acc: 0.1111
[[ 0.  0.  2.  0.  0.  0.  0.  0.  1.  0.  1.  0.  1.  0.  1.]
 [ 0.  0.  2.  0.  0.  0.  0.  0.  0.  0.  0.  0.  3.  0.  1.]
 [ 0.  0.  2.  0.  0.  0.  0.  0.  1.  0.  0.  0.  3.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  2.  0.  0.  0.  4.  0.  0.]
 [ 0.  0.  3.  0.  0.  0.  0.  0.  3.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  2.  0.  0.  0.  0.  0.  0.  0.  0.  0.  3.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  6.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  2.  0.  0.  0.  0.  0.  0.  0.  1.  0.  1.  0.  2.]
 [ 0.  0.  3.  0.  0.  0.  0.  0.  1.  0.  0.  0.  2.  0.  0.]
 [ 0.  0.  4.  0.  0.  0.  0.  0.  1.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  5.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  4.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  6.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  2.  0.  0.  0.  0.  0.  4.]
 [ 0.  0.  2.  0.  0.  0.  0.  1.

In [8]:
obj.store_model(f_name='/data/gabriel/VC/models/saved_model.pth.tar')

In [9]:
res2 = models.resnet18(pretrained=True)
res2.fc = nn.Linear(res2.fc.in_features,15)


In [10]:
obj2 = model_pip(res2,scale=True,use_gpu=False,batch_size=3,epochs=4)
#obj2.train_model()
#obj2.store_model(f_name='/data/gabriel/VC/models/saved_model.pth.tar')
obj2.load_model('/data/gabriel/VC/models/saved_model.pth.tar')

In [11]:
obj2.test(model_dir='/data/gabriel/VC/models/',n=None)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
0.11666666666666667


In [ ]:
for i,j in (b['train']):
    print(i.size())
    print(j.size())
    break