In [3]:
from torchvision import datasets,models,transforms
import torch.nn as nn
from nndev import model_pip,sample_data
CUDA_LAUNCH_BLOCKING=1 

for j in xrange(1,10):
    k=j+1
    setnumber="SET"+str(k)
    datapath="/data/Gurpreet/RUNS/VC_10/"+setnumber+"/dataset/"
    savepath="/data/Gurpreet/RUNS/VC_10/"+setnumber+"/ResNetModel_Pretrained.pth.tar"
    res = models.resnet18(pretrained=True)
    res.fc = nn.Linear(res.fc.in_features,7)
    obj = model_pip(model_in=res,scale=True,batch_size=100,use_gpu=True,gpu=1,data_path=datapath)
    model = obj.train_model(epochs=10)
    obj.store_model(f_name=savepath)

here
{'test': 6112, 'train': 20000, 'val': 2799}
('Epoch = ', 0)
('lr = ', 0.001)
traintrain Loss: 0.0038 Acc: 0.8898
[[  1.59500000e+03   3.60000000e+01   1.18000000e+02   1.10000000e+01
    1.57000000e+02   7.00000000e+00   0.00000000e+00]
 [  1.50000000e+02   1.13400000e+03   2.04000000e+02   8.00000000e+00
    1.11000000e+02   1.00000000e+00   0.00000000e+00]
 [  4.30000000e+01   1.70000000e+01   2.85800000e+03   4.20000000e+01
    2.34000000e+02   7.00000000e+00   0.00000000e+00]
 [  4.70000000e+01   4.00000000e+00   2.60000000e+01   2.50800000e+03
    3.45000000e+02   1.00000000e+00   2.00000000e+00]
 [  8.70000000e+01   8.00000000e+00   1.30000000e+01   7.40000000e+01
    8.26200000e+03   1.90000000e+01   3.00000000e+00]
 [  1.80000000e+01   3.00000000e+00   1.60000000e+01   3.00000000e+01
    2.84000000e+02   1.43700000e+03   0.00000000e+00]
 [  2.00000000e+00   3.50000000e+01   1.00000000e+00   6.00000000e+00
    3.50000000e+01   0.00000000e+00   1.00000000e+00]]
valval Loss: 

valval Loss: 0.0030 Acc: 0.9339
[[  1.92000000e+02   1.00000000e+00   5.00000000e+01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   1.97000000e+02   3.30000000e+01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   9.00000000e+00   4.32000000e+02   1.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.50000000e+01   3.00000000e+00   0.00000000e+00   3.75000000e+02
    2.10000000e+01   3.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   1.00000000e+00
    1.20400000e+03   0.00000000e+00   0.00000000e+00]
 [  4.00000000e+00   0.00000000e+00   0.00000000e+00   6.00000000e+00
    8.00000000e+00   1.99000000e+02   0.00000000e+00]
 [  0.00000000e+00   5.00000000e+00   1.00000000e+00   0.00000000e+00
    2.30000000e+01   0.00000000e+00   1.50000000e+01]]
('Epoch = ', 6)
traintrain Loss: 0.0000 Acc: 1.0000
[[ 1924.     0.     0.     0.     0.     0.    

valval Loss: 0.0033 Acc: 0.9297
[[  1.84000000e+02   2.90000000e+01   5.50000000e+01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  5.00000000e+00   2.01000000e+02   1.70000000e+01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   7.00000000e+00   4.24000000e+02   1.30000000e+01
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   3.85000000e+02
    1.00000000e+00   6.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   9.00000000e+00
    1.22000000e+03   0.00000000e+00   0.00000000e+00]
 [  4.00000000e+00   2.00000000e+00   0.00000000e+00   1.00000000e+00
    1.70000000e+01   3.37000000e+02   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    4.10000000e+01   0.00000000e+00   0.00000000e+00]]
('Epoch = ', 2)
traintrain Loss: 0.0001 Acc: 1.0000
[[  1.97100000e+03   0.00000000e+00   0.0000000

valval Loss: 0.0034 Acc: 0.9388
[[  1.97000000e+02   1.10000000e+01   6.00000000e+01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  7.00000000e+00   1.98000000e+02   1.80000000e+01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   4.34000000e+02   9.00000000e+00
    1.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   3.90000000e+02
    1.00000000e+00   1.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   7.00000000e+00
    1.22300000e+03   0.00000000e+00   0.00000000e+00]
 [  6.00000000e+00   1.00000000e+00   0.00000000e+00   0.00000000e+00
    1.80000000e+01   3.36000000e+02   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    4.10000000e+01   0.00000000e+00   0.00000000e+00]]
('Epoch = ', 8)
traintrain Loss: 0.0000 Acc: 1.0000
[[ 1971.     0.     0.     0.     0.     0.    

traintrain Loss: 0.0000 Acc: 1.0000
[[ 1943.     0.     0.     0.     0.     0.     0.]
 [    0.  1650.     0.     0.     0.     0.     0.]
 [    0.     0.  3348.     0.     0.     0.     0.]
 [    0.     0.     0.  2985.     0.     0.     0.]
 [    0.     0.     0.     0.  8580.     0.     0.]
 [    0.     0.     0.     0.     0.  1833.     0.]
 [    0.     0.     0.     0.     0.     0.    80.]]
valval Loss: 0.0021 Acc: 0.9386
[[  2.25000000e+02   3.00000000e+00   9.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  4.00000000e+00   2.08000000e+02   4.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   4.23000000e+02   3.00000000e+00
    1.00000000e+00   2.00000000e+00   0.00000000e+00]
 [  1.70000000e+01   0.00000000e+00   1.00000000e+00   3.75000000e+02
    1.10000000e+01   3.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   7.00000000e+00   1.00000000e+01   1.00000000e+01
 

valval Loss: 0.0021 Acc: 0.9470
[[  2.27000000e+02   1.00000000e+00   9.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  3.00000000e+00   2.07000000e+02   6.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   4.26000000e+02   2.00000000e+00
    1.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  9.00000000e+00   0.00000000e+00   1.00000000e+00   3.89000000e+02
    6.00000000e+00   2.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   2.00000000e+00   7.00000000e+00   7.00000000e+00
    1.16100000e+03   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+01   1.50000000e+01
    1.50000000e+01   2.87000000e+02   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    5.50000000e+01   0.00000000e+00   0.00000000e+00]]
0.95154494382
6
here
{'test': 5682, 'train': 20367, 'val': 2862}
('Epoch = ', 0)
('lr = ', 0.001)
t

traintrain Loss: 0.0000 Acc: 1.0000
[[ 1927.     0.     0.     0.     0.     0.     0.]
 [    0.  1650.     0.     0.     0.     0.     0.]
 [    0.     0.  3217.     0.     0.     0.     0.]
 [    0.     0.     0.  3069.     0.     0.     0.]
 [    0.     0.     0.     0.  8562.     0.     0.]
 [    0.     0.     0.     0.     0.  1843.     0.]
 [    0.     0.     0.     0.     0.     0.    99.]]
valval Loss: 0.0041 Acc: 0.9221
[[  1.65000000e+02   6.00000000e+00   9.20000000e+01   1.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   1.83000000e+02   2.90000000e+01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   4.20000000e+02   4.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   3.70000000e+02
    1.80000000e+01   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   3.00000000e+00   2.80000000e+01
 

valval Loss: 0.0020 Acc: 0.9446
[[  2.65000000e+02   3.70000000e+01   1.00000000e+00   1.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.10000000e+01   1.74000000e+02   3.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.50000000e+01   7.00000000e+00   4.63000000e+02   7.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   2.00000000e+00   4.14000000e+02
    5.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   5.00000000e+00
    1.22900000e+03   1.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   5.00000000e+00
    1.30000000e+01   2.71000000e+02   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00
    4.00000000e+01   0.00000000e+00   0.00000000e+00]]
('Epoch = ', 2)
traintrain Loss: 0.0001 Acc: 1.0000
[[  1.88100000e+03   0.00000000e+00   0.0000000

traintrain Loss: 0.0000 Acc: 1.0000
[[ 1881.     0.     0.     0.     0.     0.     0.]
 [    0.  1648.     0.     0.     0.     0.     0.]
 [    0.     0.  3210.     0.     0.     0.     0.]
 [    0.     0.     0.  2857.     0.     0.     0.]
 [    0.     0.     0.     0.  8585.     0.     0.]
 [    0.     0.     0.     0.     0.  1868.     0.]
 [    0.     0.     0.     0.     0.     0.    94.]]
valval Loss: 0.0018 Acc: 0.9524
[[  2.65000000e+02   3.90000000e+01   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.10000000e+01   1.85000000e+02   2.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.00000000e+01   1.00000000e+01   4.65000000e+02   7.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   7.00000000e+00   4.06000000e+02
    8.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   2.00000000e+00
 

traintrain Loss: 0.0000 Acc: 1.0000
[[ 1897.     0.     0.     0.     0.     0.     0.]
 [    0.  1669.     0.     0.     0.     0.     0.]
 [    0.     0.  3316.     0.     0.     0.     0.]
 [    0.     0.     0.  3017.     0.     0.     0.]
 [    0.     0.     0.     0.  8451.     0.     0.]
 [    0.     0.     0.     0.     0.  1970.     0.]
 [    0.     0.     0.     0.     0.     0.    99.]]
valval Loss: 0.0020 Acc: 0.9200
[[  2.54000000e+02   1.50000000e+01   3.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  9.00000000e+00   2.30000000e+02   3.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.50000000e+01   3.00000000e+00   3.77000000e+02   0.00000000e+00
    2.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   2.84000000e+02
    9.50000000e+01   0.00000000e+00   0.00000000e+00]
 [  4.00000000e+00   1.00000000e+00   1.00000000e+00   1.00000000e+00
 

valval Loss: 0.0018 Acc: 0.9214
[[  2.55000000e+02   1.60000000e+01   1.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.10000000e+01   2.25000000e+02   6.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.30000000e+01   0.00000000e+00   3.83000000e+02   0.00000000e+00
    1.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.00000000e+00   0.00000000e+00   1.00000000e+00   2.80000000e+02
    9.80000000e+01   0.00000000e+00   0.00000000e+00]
 [  3.00000000e+00   1.00000000e+00   1.00000000e+00   4.00000000e+00
    1.23400000e+03   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.80000000e+01
    1.30000000e+01   1.95000000e+02   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    3.20000000e+01   0.00000000e+00   7.00000000e+00]]
0.921400500179
4
here
{'test': 5806, 'train': 20352, 'val': 2802}
('Epoch = ', 0)
('lr = ', 0.001)


traintrain Loss: 0.0000 Acc: 1.0000
[[ 1978.     0.     0.     0.     0.     0.     0.]
 [    0.  1620.     0.     0.     0.     0.     0.]
 [    0.     0.  3240.     0.     0.     0.     0.]
 [    0.     0.     0.  2986.     0.     0.     0.]
 [    0.     0.     0.     0.  8681.     0.     0.]
 [    0.     0.     0.     0.     0.  1753.     0.]
 [    0.     0.     0.     0.     0.     0.    94.]]
valval Loss: 0.0023 Acc: 0.9036
[[  2.21000000e+02   1.10000000e+01   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.90000000e+01   1.72000000e+02   2.20000000e+01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.10000000e+01   2.00000000e+01   4.50000000e+02   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  4.00000000e+00   0.00000000e+00   3.30000000e+01   2.88000000e+02
    3.10000000e+01   1.40000000e+01   0.00000000e+00]
 [  0.00000000e+00   4.00000000e+00   1.00000000e+00   3.00000000e+00
 

valval Loss: 0.0031 Acc: 0.9106
[[  2.65000000e+02   1.10000000e+01   2.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.60000000e+01   1.35000000e+02   4.90000000e+01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.00000000e+00   5.50000000e+01   4.36000000e+02   1.60000000e+01
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   3.00000000e+00   3.99000000e+02
    1.20000000e+01   1.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   2.00000000e+00   1.10000000e+01
    1.23200000e+03   1.70000000e+01   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   3.00000000e+00   0.00000000e+00
    6.00000000e+00   1.80000000e+02   0.00000000e+00]
 [  0.00000000e+00   4.00000000e+00   0.00000000e+00   0.00000000e+00
    4.00000000e+01   0.00000000e+00   0.00000000e+00]]
('Epoch = ', 1)
traintrain Loss: 0.0002 Acc: 0.9990
[[  1.96800000e+03   3.00000000e+00   1.0000000

traintrain Loss: 0.0000 Acc: 1.0000
[[ 1972.     0.     0.     0.     0.     0.     0.]
 [    0.  1670.     0.     0.     0.     0.     0.]
 [    0.     0.  3181.     0.     0.     0.     0.]
 [    0.     0.     0.  2913.     0.     0.     0.]
 [    0.     0.     0.     0.  8452.     0.     0.]
 [    0.     0.     0.     0.     0.  1838.     0.]
 [    0.     0.     0.     0.     0.     0.    96.]]
valval Loss: 0.0024 Acc: 0.9305
[[  2.75000000e+02   3.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.90000000e+01   1.46000000e+02   3.50000000e+01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   4.40000000e+01   4.50000000e+02   1.50000000e+01
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   3.00000000e+00   4.06000000e+02
    5.00000000e+00   1.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   4.00000000e+00
 

traintrain Loss: 0.0001 Acc: 1.0000
[[ 1915.     0.     0.     0.     0.     0.     0.]
 [    0.  1672.     0.     0.     0.     0.     0.]
 [    0.     0.  3176.     0.     0.     0.     0.]
 [    0.     0.     0.  2989.     0.     0.     0.]
 [    0.     0.     0.     0.  8370.     0.     0.]
 [    0.     0.     0.     0.     0.  1882.     0.]
 [    0.     0.     0.     0.     0.     0.    99.]]
valval Loss: 0.0013 Acc: 0.9533
[[  2.67000000e+02   1.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.40000000e+01   1.88000000e+02   3.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   9.00000000e+00   4.36000000e+02   2.00000000e+01
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   3.96000000e+02
    2.20000000e+01   3.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   3.00000000e+00
 

valval Loss: 0.0013 Acc: 0.9502
[[  2.66000000e+02   2.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  4.00000000e+00   1.99000000e+02   2.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   2.30000000e+01   4.25000000e+02   1.70000000e+01
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   3.98000000e+02
    2.30000000e+01   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   4.00000000e+00   0.00000000e+00   1.00000000e+00
    1.27900000e+03   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   2.80000000e+01
    1.00000000e+00   1.81000000e+02   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    3.80000000e+01   0.00000000e+00   1.00000000e+00]]
('Epoch = ', 8)
traintrain Loss: 0.0000 Acc: 1.0000
[[ 1915.     0.     0.     0.     0.     0.    

In [1]:
from torchvision import datasets,models,transforms
import torch.nn as nn
from nndev import model_pip,sample_data
CUDA_LAUNCH_BLOCKING=1 

setnumber="SET1"
res = models.resnet18(pretrained=True)
res.fc = nn.Linear(res.fc.in_features,7)
obj = model_pip(model_in=res,scale=True,batch_size=100,use_gpu=True,gpu=1,data_path="/data/Gurpreet/RUNS/VC_10/"+str(setnumber)+"/dataset/")
obj.load_model("/data/Gurpreet/RUNS/VC_10/"+str(setnumber)+"/ResNetModel_Pretrained.pth.tar")
obj.test(model_dir="/data/Gurpreet/RUNS/VC_10/"+str(setnumber)+"/",n=None,test_on=True)

(7, 7)
('test accuracy= ', 0.28240580712063601)
[[  4.20000000e+02   2.10000000e+01   3.70000000e+01   0.00000000e+00
    4.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.20000000e+01   4.27000000e+02   3.50000000e+01   0.00000000e+00
    2.20000000e+01   0.00000000e+00   0.00000000e+00]
 [  3.70000000e+01   7.70000000e+01   7.87000000e+02   1.50000000e+01
    4.40000000e+01   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   4.00000000e+00   1.60000000e+01   6.70000000e+02
    1.61000000e+02   3.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   6.00000000e+00   0.00000000e+00   2.40000000e+01
    2.42100000e+03   6.00000000e+00   0.00000000e+00]
 [  1.20000000e+01   0.00000000e+00   0.00000000e+00   5.00000000e+00
    2.50000000e+01   4.56000000e+02   0.00000000e+00]
 [  0.00000000e+00   1.00000000e+00   0.00000000e+00   0.00000000e+00
    3.80000000e+01   0.00000000e+00   0.00000000e+00]]
