In [1]:
from torchvision import datasets,models,transforms
import torch.nn as nn
from nndev import model_pip
 

for j in xrange(0,10):
    k=j+1
    setnumber="SET"+str(k)
    Model_name="ResNetModel_Pretrained_7_views_bs_100_e_10_28062017_0640.pth.tar"
    datapath="/data/Gurpreet/RUNS/VC_10/"+setnumber+"/dataset/"
    savepath="/data/Gurpreet/RUNS/VC_10/"+setnumber+"/"+Model_name
    res = models.resnet18(pretrained=True)
    res.fc = nn.Linear(res.fc.in_features,7)
    obj = model_pip(model_in=res,scale=True,batch_size=100,use_gpu=True,gpu=1,data_path=datapath)
    model = obj.train_model(epochs=10)
    obj.store_model(f_name=savepath)
    mdir="/data/Gurpreet/RUNS/VC_10/"+str(setnumber)+"/"
      
    obj.test(model_dir=mdir,model_name=Model_name,save_miscl = True,test_on=True,n='None',random_crop=False,folder='misc')
    #obj.test(model_dir=mdir,test_on=True,model_name="ResNetModel_Pretrained.pth.tar",save_miscl = True)

here
{'test': 5786, 'train': 20224, 'val': 2950}
('Epoch = ', 0)
('lr = ', 0.001)
traintrain Loss: 0.0038607558 
Acc: 0.8847
[[  1.57500000e+03   7.30000000e+01   1.38000000e+02   5.00000000e+00
    1.90000000e+02   7.00000000e+00   1.20000000e+01]
 [  9.50000000e+01   1.18300000e+03   2.22000000e+02   1.00000000e+00
    1.15000000e+02   0.00000000e+00   5.00000000e+00]
 [  1.00000000e+01   2.90000000e+01   2.90400000e+03   1.30000000e+01
    2.44000000e+02   6.00000000e+00   1.20000000e+01]
 [  7.00000000e+00   1.10000000e+01   2.10000000e+01   2.45000000e+03
    4.29000000e+02   1.00000000e+00   1.80000000e+01]
 [  1.00000000e+00   7.80000000e+01   1.80000000e+01   5.50000000e+01
    8.28500000e+03   4.00000000e+00   5.20000000e+01]
 [  2.00000000e+00   1.90000000e+01   1.50000000e+01   2.60000000e+01
    3.12000000e+02   1.49500000e+03   1.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   2.00000000e+00   0.00000000e+00
    7.90000000e+01   4.00000000e+00   0.00000000e+00]]
valval

valval Loss: 0.0042793864 
Acc: 0.8695
[[  2.07000000e+02   3.60000000e+01   1.80000000e+01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  3.40000000e+01   1.27000000e+02   4.50000000e+01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   2.00000000e+00   4.56000000e+02   1.50000000e+01
    1.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  6.00000000e+00   0.00000000e+00   2.00000000e+00   3.27000000e+02
    8.20000000e+01   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   2.70000000e+01
    1.27600000e+03   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   8.00000000e+00   2.70000000e+01
    2.70000000e+01   1.72000000e+02   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    5.50000000e+01   0.00000000e+00   0.00000000e+00]]
('Epoch = ', 5)
traintrain Loss: 0.0000234772 
Acc: 1.0000
[[ 2000.     0.     0.     0.    

here
{'test': 6112, 'train': 20000, 'val': 2799}
('Epoch = ', 0)
('lr = ', 0.001)
traintrain Loss: 0.0041488010 
Acc: 0.8762
[[  1.46200000e+03   7.00000000e+01   1.57000000e+02   1.90000000e+01
    2.08000000e+02   6.00000000e+00   2.00000000e+00]
 [  1.59000000e+02   1.07500000e+03   1.99000000e+02   1.00000000e+01
    1.61000000e+02   0.00000000e+00   4.00000000e+00]
 [  2.20000000e+01   1.60000000e+01   2.81200000e+03   5.10000000e+01
    2.77000000e+02   1.30000000e+01   1.00000000e+01]
 [  0.00000000e+00   4.00000000e+00   6.70000000e+01   2.48200000e+03
    3.78000000e+02   1.00000000e+00   1.00000000e+00]
 [  1.00000000e+00   1.10000000e+01   1.42000000e+02   6.40000000e+01
    8.23800000e+03   1.00000000e+01   0.00000000e+00]
 [  1.00000000e+00   1.00000000e+00   3.40000000e+01   3.10000000e+01
    2.88000000e+02   1.43300000e+03   0.00000000e+00]
 [  0.00000000e+00   5.00000000e+00   0.00000000e+00   0.00000000e+00
    5.10000000e+01   1.00000000e+00   2.30000000e+01]]
valval

traintrain Loss: 0.0000259293 
Acc: 1.0000
[[ 1924.     0.     0.     0.     0.     0.     0.]
 [    0.  1608.     0.     0.     0.     0.     0.]
 [    0.     0.  3201.     0.     0.     0.     0.]
 [    0.     0.     0.  2933.     0.     0.     0.]
 [    0.     0.     0.     0.  8466.     0.     0.]
 [    0.     0.     0.     0.     0.  1788.     0.]
 [    0.     0.     0.     0.     0.     0.    80.]]
valval Loss: 0.0031124277 
Acc: 0.9121
[[  1.82000000e+02   1.10000000e+01   5.00000000e+01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   2.08000000e+02   2.10000000e+01   0.00000000e+00
    1.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.00000000e+00   1.10000000e+01   4.29000000e+02   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  5.00000000e+00   0.00000000e+00   0.00000000e+00   3.64000000e+02
    4.80000000e+01   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   2.

valval Loss: 0.0041673228 
Acc: 0.8729
[[  1.51000000e+02   5.90000000e+01   5.80000000e+01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.10000000e+01   1.81000000e+02   3.10000000e+01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   2.10000000e+01   3.99000000e+02   2.30000000e+01
    0.00000000e+00   1.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   3.64000000e+02
    3.00000000e+00   2.50000000e+01   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   9.00000000e+00
    1.22100000e+03   0.00000000e+00   0.00000000e+00]
 [  6.00000000e+00   0.00000000e+00   5.00000000e+00   0.00000000e+00
    8.30000000e+01   2.67000000e+02   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    4.10000000e+01   0.00000000e+00   0.00000000e+00]]
('Epoch = ', 1)
traintrain Loss: 0.0002213681 
Acc: 0.9995
[[  1.97000000e+03   0.00000000e+

valval Loss: 0.0040099418 
Acc: 0.9054
[[  1.81000000e+02   3.40000000e+01   5.30000000e+01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.00000000e+00   1.98000000e+02   2.30000000e+01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   1.30000000e+01   4.07000000e+02   2.40000000e+01
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   3.80000000e+02
    1.00000000e+00   1.10000000e+01   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   8.00000000e+00
    1.22200000e+03   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   2.00000000e+00   0.00000000e+00
    6.80000000e+01   2.91000000e+02   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    4.10000000e+01   0.00000000e+00   0.00000000e+00]]
('Epoch = ', 7)
('lr = ', 0.0001)
traintrain Loss: 0.0000179259 
Acc: 1.0000
[[ 1971.     0.

valval Loss: 0.0031495879 
Acc: 0.9242
[[  2.23000000e+02   3.00000000e+00   1.10000000e+01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  7.00000000e+00   1.91000000e+02   1.80000000e+01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   2.00000000e+00   4.24000000e+02   2.00000000e+00
    0.00000000e+00   1.00000000e+00   0.00000000e+00]
 [  3.00000000e+00   0.00000000e+00   1.00000000e+00   3.46000000e+02
    2.70000000e+01   3.00000000e+01   0.00000000e+00]
 [  0.00000000e+00   5.00000000e+00   5.00000000e+00   1.60000000e+01
    1.14300000e+03   8.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   5.00000000e+00   9.00000000e+00
    8.00000000e+00   3.05000000e+02   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    5.10000000e+01   4.00000000e+00   0.00000000e+00]]
('Epoch = ', 2)
traintrain Loss: 0.0000887758 
Acc: 1.0000
[[  1.94300000e+03   0.00000000e+

valval Loss: 0.0027420515 
Acc: 0.9417
[[  2.27000000e+02   4.00000000e+00   6.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  3.00000000e+00   2.07000000e+02   6.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   2.00000000e+00   4.23000000e+02   4.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.00000000e+00   1.00000000e+00   0.00000000e+00   3.61000000e+02
    1.70000000e+01   2.60000000e+01   0.00000000e+00]
 [  0.00000000e+00   2.00000000e+00   3.00000000e+00   9.00000000e+00
    1.16000000e+03   3.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   1.00000000e+00   3.00000000e+00   1.00000000e+01
    9.00000000e+00   3.04000000e+02   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    5.30000000e+01   2.00000000e+00   0.00000000e+00]]
('Epoch = ', 8)
traintrain Loss: 0.0000169617 
Acc: 1.0000
[[ 1943.     0.     0.     0.    

traintrain Loss: 0.0000499548 
Acc: 1.0000
[[ 1927.     0.     0.     0.     0.     0.     0.]
 [    0.  1650.     0.     0.     0.     0.     0.]
 [    0.     0.  3217.     0.     0.     0.     0.]
 [    0.     0.     0.  3069.     0.     0.     0.]
 [    0.     0.     0.     0.  8562.     0.     0.]
 [    0.     0.     0.     0.     0.  1843.     0.]
 [    0.     0.     0.     0.     0.     0.    99.]]
valval Loss: 0.0043178243 
Acc: 0.9022
[[  1.72000000e+02   6.00000000e+00   8.50000000e+01   1.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   1.77000000e+02   3.50000000e+01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   1.70000000e+01   4.01000000e+02   6.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   3.44000000e+02
    1.40000000e+01   3.00000000e+01   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   4.00000000e+00   2.

valval Loss: 0.0044915310 
Acc: 0.9071
[[  1.72000000e+02   8.00000000e+00   8.30000000e+01   0.00000000e+00
    1.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   1.78000000e+02   3.40000000e+01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   1.20000000e+01   4.06000000e+02   6.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.00000000e+00   0.00000000e+00   2.00000000e+00   3.39000000e+02
    1.80000000e+01   2.90000000e+01   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.60000000e+01
    1.17700000e+03   1.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.40000000e+01   0.00000000e+00
    0.00000000e+00   3.24000000e+02   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    4.10000000e+01   0.00000000e+00   0.00000000e+00]]
0.910901467505
6
here
('test accuracy= ', 0.92344244984160506)
[[  4.82000000e+02   2.800000

traintrain Loss: 0.0000326065 
Acc: 1.0000
[[ 1881.     0.     0.     0.     0.     0.     0.]
 [    0.  1648.     0.     0.     0.     0.     0.]
 [    0.     0.  3210.     0.     0.     0.     0.]
 [    0.     0.     0.  2857.     0.     0.     0.]
 [    0.     0.     0.     0.  8585.     0.     0.]
 [    0.     0.     0.     0.     0.  1868.     0.]
 [    0.     0.     0.     0.     0.     0.    94.]]
valval Loss: 0.0016637000 
Acc: 0.9611
[[  2.74000000e+02   3.00000000e+01   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  7.00000000e+00   1.91000000e+02   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  3.00000000e+00   9.00000000e+00   4.76000000e+02   4.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   2.00000000e+00   4.09000000e+02
    1.00000000e+01   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.

here
{'test': 5742, 'train': 20419, 'val': 2799}
('Epoch = ', 0)
('lr = ', 0.001)
traintrain Loss: 0.0037771758 
Acc: 0.8883
[[  1.50400000e+03   7.30000000e+01   1.34000000e+02   1.00000000e+00
    1.74000000e+02   1.00000000e+01   1.00000000e+00]
 [  1.10000000e+02   1.23100000e+03   2.10000000e+02   3.00000000e+00
    1.14000000e+02   0.00000000e+00   1.00000000e+00]
 [  3.70000000e+01   3.00000000e+01   2.95100000e+03   4.60000000e+01
    2.38000000e+02   1.20000000e+01   2.00000000e+00]
 [  4.40000000e+01   5.00000000e+00   1.70000000e+01   2.57800000e+03
    3.71000000e+02   1.00000000e+00   1.00000000e+00]
 [  1.17000000e+02   7.00000000e+00   5.10000000e+01   3.80000000e+01
    8.22000000e+03   1.10000000e+01   7.00000000e+00]
 [  2.90000000e+01   2.00000000e+00   3.10000000e+01   4.70000000e+01
    2.26000000e+02   1.63400000e+03   1.00000000e+00]
 [  8.00000000e+00   9.00000000e+00   3.00000000e+00   0.00000000e+00
    4.10000000e+01   1.80000000e+01   2.00000000e+01]]
valval

traintrain Loss: 0.0000247441 
Acc: 1.0000
[[ 1897.     0.     0.     0.     0.     0.     0.]
 [    0.  1669.     0.     0.     0.     0.     0.]
 [    0.     0.  3316.     0.     0.     0.     0.]
 [    0.     0.     0.  3017.     0.     0.     0.]
 [    0.     0.     0.     0.  8451.     0.     0.]
 [    0.     0.     0.     0.     0.  1970.     0.]
 [    0.     0.     0.     0.     0.     0.    99.]]
valval Loss: 0.0023172219 
Acc: 0.9121
[[  2.60000000e+02   1.10000000e+01   1.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.30000000e+01   2.27000000e+02   2.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.80000000e+01   4.00000000e+00   3.65000000e+02   0.00000000e+00
    1.00000000e+01   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.20000000e+01   2.43000000e+02
    1.25000000e+02   0.00000000e+00   0.00000000e+00]
 [  2.00000000e+00   0.00000000e+00   0.00000000e+00   1.

valval Loss: 0.0031729234 
Acc: 0.8997
[[  2.08000000e+02   2.20000000e+01   0.00000000e+00   0.00000000e+00
    0.00000000e+00   2.00000000e+00   0.00000000e+00]
 [  1.30000000e+01   1.76000000e+02   2.40000000e+01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.00000000e+00   1.10000000e+01   4.69000000e+02   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.00000000e+00   0.00000000e+00   1.60000000e+01   2.95000000e+02
    4.10000000e+01   1.70000000e+01   0.00000000e+00]
 [  0.00000000e+00   1.00000000e+01   2.00000000e+00   7.00000000e+00
    1.18200000e+03   5.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   2.60000000e+01   2.50000000e+01
    1.40000000e+01   1.91000000e+02   0.00000000e+00]
 [  1.00000000e+00   6.00000000e+00   1.00000000e+00   0.00000000e+00
    3.60000000e+01   0.00000000e+00   0.00000000e+00]]
('Epoch = ', 1)
traintrain Loss: 0.0002187131 
Acc: 0.9988
[[  1.97300000e+03   2.00000000e+

traintrain Loss: 0.0000177188 
Acc: 1.0000
[[ 1978.     0.     0.     0.     0.     0.     0.]
 [    0.  1620.     0.     0.     0.     0.     0.]
 [    0.     0.  3240.     0.     0.     0.     0.]
 [    0.     0.     0.  2986.     0.     0.     0.]
 [    0.     0.     0.     0.  8681.     0.     0.]
 [    0.     0.     0.     0.     0.  1753.     0.]
 [    0.     0.     0.     0.     0.     0.    94.]]
valval Loss: 0.0022939013 
Acc: 0.9176
[[  2.11000000e+02   1.90000000e+01   0.00000000e+00   2.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.00000000e+00   1.93000000e+02   1.90000000e+01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  6.00000000e+00   6.00000000e+00   4.69000000e+02   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.00000000e+00   0.00000000e+00   2.60000000e+01   2.94000000e+02
    3.00000000e+01   1.90000000e+01   0.00000000e+00]
 [  0.00000000e+00   9.00000000e+00   2.00000000e+00   2.

valval Loss: 0.0022174433 
Acc: 0.9322
[[  2.65000000e+02   1.10000000e+01   1.00000000e+00   0.00000000e+00
    0.00000000e+00   1.00000000e+00   0.00000000e+00]
 [  2.80000000e+01   1.67000000e+02   1.50000000e+01   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   3.00000000e+01   4.57000000e+02   2.20000000e+01
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   9.00000000e+00   3.95000000e+02
    1.10000000e+01   0.00000000e+00   0.00000000e+00]
 [  2.00000000e+00   0.00000000e+00   0.00000000e+00   6.00000000e+00
    1.25000000e+03   4.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   2.00000000e+00
    1.10000000e+01   1.76000000e+02   0.00000000e+00]
 [  1.00000000e+00   1.10000000e+01   0.00000000e+00   0.00000000e+00
    3.20000000e+01   0.00000000e+00   0.00000000e+00]]
('Epoch = ', 2)
traintrain Loss: 0.0000809320 
Acc: 0.9998
[[  1.97100000e+03   0.00000000e+

valval Loss: 0.0020445652 
Acc: 0.9367
[[  2.74000000e+02   3.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   1.00000000e+00   0.00000000e+00]
 [  3.20000000e+01   1.67000000e+02   1.00000000e+01   0.00000000e+00
    1.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   2.00000000e+01   4.56000000e+02   3.30000000e+01
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   5.00000000e+00   3.99000000e+02
    1.10000000e+01   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   9.00000000e+00
    1.25300000e+03   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   1.00000000e+00
    1.30000000e+01   1.74000000e+02   0.00000000e+00]
 [  0.00000000e+00   9.00000000e+00   0.00000000e+00   0.00000000e+00
    3.50000000e+01   0.00000000e+00   0.00000000e+00]]
('Epoch = ', 8)
traintrain Loss: 0.0000172962 
Acc: 1.0000
[[ 1972.     0.     0.     0.    

traintrain Loss: 0.0003401979 
Acc: 0.9997
[[  1.91400000e+03   0.00000000e+00   1.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   1.67200000e+03   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   3.17400000e+03   0.00000000e+00
    2.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   2.98700000e+03
    2.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.00000000e+00
    8.36900000e+03   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   1.88200000e+03   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   9.90000000e+01]]
valval Loss: 0.0017184057 
Acc: 0.9506
[[  2.66000000e+02   2.00000000e+00   0.00000000e

traintrain Loss: 0.0000160755 
Acc: 1.0000
[[ 1915.     0.     0.     0.     0.     0.     0.]
 [    0.  1672.     0.     0.     0.     0.     0.]
 [    0.     0.  3176.     0.     0.     0.     0.]
 [    0.     0.     0.  2989.     0.     0.     0.]
 [    0.     0.     0.     0.  8370.     0.     0.]
 [    0.     0.     0.     0.     0.  1882.     0.]
 [    0.     0.     0.     0.     0.     0.    99.]]
valval Loss: 0.0015551187 
Acc: 0.9530
[[  2.66000000e+02   2.00000000e+00   0.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  5.00000000e+00   1.97000000e+02   3.00000000e+00   0.00000000e+00
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   3.10000000e+01   3.93000000e+02   4.10000000e+01
    0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   4.14000000e+02
    7.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   1.