In [ ]:
from torchvision import datasets,models,transforms
import torch.nn as nn
from nndev import model_pip,sample_data
CUDA_LAUNCH_BLOCKING=1 

for j in xrange(0,1):
    k=j+1
    setnumber="SET"+str(k)
    datapath="/data/Gurpreet/RUNS/VC_10/"+setnumber+"/dataset/"
    savepath="/data/Gurpreet/RUNS/VC_10/"+setnumber+"/ResNetModel_Scratch_lr_0_1_epochs_100.pth.tar"
    res = models.resnet18(pretrained=False)
    res.fc = nn.Linear(res.fc.in_features,7)
    obj = model_pip(model_in=res,scale=True,batch_size=120,use_gpu=True,gpu=3,data_path=datapath,lr=0.1,lr_decay_epoch=30)
    model = obj.train_model(epochs=50)
    obj.store_model(f_name=savepath)

here
{'test': 5786, 'train': 20224, 'val': 2950}
('Epoch = ', 0)
('lr = ', 0.1)
traintrain Loss: 0.0070 Acc: 0.7352
[[  1.12900000e+03   1.67000000e+02   2.94000000e+02   4.30000000e+01
    3.58000000e+02   9.00000000e+00   0.00000000e+00]
 [  3.28000000e+02   5.38000000e+02   3.90000000e+02   2.90000000e+01
    3.21000000e+02   1.50000000e+01   0.00000000e+00]
 [  1.37000000e+02   9.00000000e+01   2.23100000e+03   1.02000000e+02
    6.30000000e+02   2.80000000e+01   0.00000000e+00]
 [  2.60000000e+01   1.00000000e+00   9.90000000e+01   2.14800000e+03
    6.12000000e+02   5.10000000e+01   0.00000000e+00]
 [  7.00000000e+01   9.00000000e+00   2.54000000e+02   3.63000000e+02
    7.68200000e+03   1.15000000e+02   0.00000000e+00]
 [  2.60000000e+01   1.00000000e+01   6.90000000e+01   1.10000000e+02
    5.15000000e+02   1.14000000e+03   0.00000000e+00]
 [  7.00000000e+00   4.40000000e+01   7.00000000e+00   0.00000000e+00
    2.70000000e+01   0.00000000e+00   0.00000000e+00]]
valval Loss: 0.

traintrain Loss: 0.0000 Acc: 1.0000
[[ 2000.     0.     0.     0.     0.     0.     0.]
 [    0.  1621.     0.     0.     0.     0.     0.]
 [    0.     0.  3218.     0.     0.     0.     0.]
 [    0.     0.     0.  2937.     0.     0.     0.]
 [    0.     0.     0.     0.  8493.     0.     0.]
 [    0.     0.     0.     0.     0.  1870.     0.]
 [    0.     0.     0.     0.     0.     0.    85.]]
valval Loss: 0.0100 Acc: 0.7793
[[  2.04000000e+02   1.80000000e+01   1.70000000e+01   0.00000000e+00
    6.00000000e+00   0.00000000e+00   1.60000000e+01]
 [  2.50000000e+01   1.06000000e+02   6.80000000e+01   0.00000000e+00
    7.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  7.00000000e+00   4.70000000e+01   3.61000000e+02   1.00000000e+01
    4.90000000e+01   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00   2.97000000e+02
    1.12000000e+02   7.00000000e+00   0.00000000e+00]
 [  6.00000000e+00   0.00000000e+00   1.00000000e+01   1.10000000e+02
 

valval Loss: 0.0097 Acc: 0.7946
[[  2.12000000e+02   1.60000000e+01   1.50000000e+01   2.00000000e+00
    4.00000000e+00   1.00000000e+00   1.10000000e+01]
 [  2.30000000e+01   1.05000000e+02   6.90000000e+01   0.00000000e+00
    9.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  6.00000000e+00   3.40000000e+01   3.82000000e+02   8.00000000e+00
    4.30000000e+01   0.00000000e+00   1.00000000e+00]
 [  1.00000000e+00   0.00000000e+00   1.00000000e+00   3.00000000e+02
    1.10000000e+02   5.00000000e+00   0.00000000e+00]
 [  5.00000000e+00   0.00000000e+00   7.00000000e+00   1.07000000e+02
    1.16200000e+03   2.10000000e+01   1.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   3.80000000e+01   2.00000000e+00
    9.00000000e+00   1.83000000e+02   2.00000000e+00]
 [  2.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
    5.30000000e+01   0.00000000e+00   0.00000000e+00]]
('Epoch = ', 13)
traintrain Loss: 0.0000 Acc: 1.0000
[[ 2000.     0.     0.     0.     0.     0.   

traintrain Loss: 0.0000 Acc: 1.0000
[[ 2000.     0.     0.     0.     0.     0.     0.]
 [    0.  1621.     0.     0.     0.     0.     0.]
 [    0.     0.  3218.     0.     0.     0.     0.]
 [    0.     0.     0.  2937.     0.     0.     0.]
 [    0.     0.     0.     0.  8493.     0.     0.]
 [    0.     0.     0.     0.     0.  1870.     0.]
 [    0.     0.     0.     0.     0.     0.    85.]]
valval Loss: 0.0101 Acc: 0.7892
[[  2.12000000e+02   1.40000000e+01   2.40000000e+01   0.00000000e+00
    3.00000000e+00   0.00000000e+00   8.00000000e+00]
 [  2.10000000e+01   1.07000000e+02   6.90000000e+01   0.00000000e+00
    9.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  4.00000000e+00   3.60000000e+01   3.87000000e+02   7.00000000e+00
    4.00000000e+01   0.00000000e+00   0.00000000e+00]
 [  3.00000000e+00   1.00000000e+00   0.00000000e+00   2.85000000e+02
    1.17000000e+02   1.00000000e+01   1.00000000e+00]
 [  5.00000000e+00   0.00000000e+00   1.00000000e+01   1.09000000e+02
 