In [1]:
from torchvision import datasets,models,transforms
import torch.nn as nn
from nndev import model_pip
#CUDA_LAUNCH_BLOCKING=1 

for j in xrange(0,10):
    k=j+1
    setnumber="SET"+str(k)
    Model_name="ResNetModel_Pretrained_3_views_bs_30_e_20_28062017_0705.pth.tar"
    datapath="/data/Gurpreet/RUNS/VC_11/"+setnumber+"/dataset/"
    savepath="/data/Gurpreet/RUNS/VC_11/"+setnumber+"/ResNetModel.pth.tar"
    res = models.resnet18(pretrained=True)
    res.fc = nn.Linear(res.fc.in_features,3)
    obj = model_pip(model_in=res,scale=True,batch_size=30,use_gpu=True,gpu=2,data_path=datapath)
    model = obj.train_model(epochs=20)
    obj.store_model(f_name=savepath)
    mdir="/data/Gurpreet/RUNS/VC_10/"+str(setnumber)+"/"
    obj.test(model_dir=mdir,model_name=Model_name,save_miscl = True,test_on=True,n='None',random_crop=False,folder='misc')
    del (obj)

here
{'test': 2296, 'train': 8155, 'val': 1152}
('Epoch = ', 0)
('lr = ', 0.001)
traintrain Loss: 0.0036576095 
Acc: 0.9643
[[ 1879.    96.    25.]
 [   34.  3101.    83.]
 [    9.    44.  2884.]]
valval Loss: 0.0085998947 
Acc: 0.9045
[[ 225.   36.    0.]
 [   8.  420.   46.]
 [   6.   14.  397.]]
('Epoch = ', 1)
traintrain Loss: 0.0001381148 
Acc: 0.9999
[[  2.00000000e+03   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   3.21800000e+03   0.00000000e+00]
 [  0.00000000e+00   1.00000000e+00   2.93600000e+03]]
valval Loss: 0.0095962006 
Acc: 0.8984
[[ 220.   37.    4.]
 [   5.  406.   63.]
 [   1.    7.  409.]]
('Epoch = ', 2)
traintrain Loss: 0.0000603603 
Acc: 1.0000
[[ 2000.     0.     0.]
 [    0.  3218.     0.]
 [    0.     0.  2937.]]
valval Loss: 0.0084595733 
Acc: 0.9036
[[ 231.   29.    1.]
 [   5.  410.   59.]
 [   7.   10.  400.]]
('Epoch = ', 3)
traintrain Loss: 0.0000399968 
Acc: 1.0000
[[ 2000.     0.     0.]
 [    0.  3218.     0.]
 [    0.     0.  2937.]]
valval L

valval Loss: 0.0157681899 
Acc: 0.9419
[[ 193.   50.    0.]
 [   4.  437.    1.]
 [   9.    0.  408.]]
('Epoch = ', 13)
traintrain Loss: 0.0000169852 
Acc: 1.0000
[[ 1924.     0.     0.]
 [    0.  3201.     0.]
 [    0.     0.  2933.]]
valval Loss: 0.0166708598 
Acc: 0.9465
[[ 193.   50.    0.]
 [   1.  440.    1.]
 [   6.    1.  410.]]
('Epoch = ', 14)
('lr = ', 1.0000000000000003e-05)
traintrain Loss: 0.0000147568 
Acc: 1.0000
[[ 1924.     0.     0.]
 [    0.  3201.     0.]
 [    0.     0.  2933.]]
valval Loss: 0.0156175277 
Acc: 0.9456
[[ 193.   50.    0.]
 [   0.  440.    2.]
 [   8.    0.  409.]]
('Epoch = ', 15)
traintrain Loss: 0.0000121429 
Acc: 1.0000
[[ 1924.     0.     0.]
 [    0.  3201.     0.]
 [    0.     0.  2933.]]
valval Loss: 0.0160114401 
Acc: 0.9474
[[ 193.   50.    0.]
 [   2.  439.    1.]
 [   5.    0.  412.]]
('Epoch = ', 16)
traintrain Loss: 0.0000230884 
Acc: 1.0000
[[ 1924.     0.     0.]
 [    0.  3201.     0.]
 [    0.     0.  2933.]]
valval Loss: 0.0160271

traintrain Loss: 0.0000263229 
Acc: 1.0000
[[ 1943.     0.     0.]
 [    0.  3348.     0.]
 [    0.     0.  2985.]]
valval Loss: 0.0011041528 
Acc: 0.9860
[[ 226.   11.    0.]
 [   0.  425.    4.]
 [   0.    0.  407.]]
('Epoch = ', 5)
traintrain Loss: 0.0000225805 
Acc: 1.0000
[[ 1943.     0.     0.]
 [    0.  3348.     0.]
 [    0.     0.  2985.]]
valval Loss: 0.0011682974 
Acc: 0.9888
[[ 232.    5.    0.]
 [   0.  422.    7.]
 [   0.    0.  407.]]
('Epoch = ', 6)
traintrain Loss: 0.0000216611 
Acc: 1.0000
[[ 1943.     0.     0.]
 [    0.  3348.     0.]
 [    0.     0.  2985.]]
valval Loss: 0.0006779055 
Acc: 0.9944
[[ 236.    1.    0.]
 [   0.  424.    5.]
 [   0.    0.  407.]]
('Epoch = ', 7)
('lr = ', 0.0001)
traintrain Loss: 0.0000182917 
Acc: 1.0000
[[ 1943.     0.     0.]
 [    0.  3348.     0.]
 [    0.     0.  2985.]]
valval Loss: 0.0010300726 
Acc: 0.9925
[[ 237.    0.    0.]
 [   0.  421.    8.]
 [   0.    0.  407.]]
('Epoch = ', 8)
traintrain Loss: 0.0000180068 
Acc: 1.0000

valval Loss: 0.0211715248 
Acc: 0.9155
[[ 181.   83.    0.]
 [   1.  419.    4.]
 [   2.    1.  386.]]
('Epoch = ', 16)
traintrain Loss: 0.0000185881 
Acc: 1.0000
[[ 1927.     0.     0.]
 [    0.  3217.     0.]
 [    0.     0.  3069.]]
valval Loss: 0.0215270477 
Acc: 0.9155
[[ 183.   81.    0.]
 [   1.  417.    6.]
 [   2.    1.  386.]]
('Epoch = ', 17)
traintrain Loss: 0.0000229368 
Acc: 0.9999
[[  1.92600000e+03   1.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   3.21700000e+03   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   3.06900000e+03]]
valval Loss: 0.0187027862 
Acc: 0.9276
[[ 203.   61.    0.]
 [   9.  407.    8.]
 [   0.    0.  389.]]
('Epoch = ', 18)
traintrain Loss: 0.0000254642 
Acc: 0.9999
[[  1.92700000e+03   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   3.21700000e+03   0.00000000e+00]
 [  1.00000000e+00   0.00000000e+00   3.06800000e+03]]
valval Loss: 0.0208136559 
Acc: 0.9239
[[ 190.   74.    0.]
 [   2.  417.    5.]
 [   0.    1.  388.]]
('Epoch =

traintrain Loss: 0.0000382503 
Acc: 0.9999
[[  1.89700000e+03   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   3.31600000e+03   0.00000000e+00]
 [  1.00000000e+00   0.00000000e+00   3.01600000e+03]]
valval Loss: 0.0034344280 
Acc: 0.9571
[[ 262.   10.    0.]
 [   9.  388.    0.]
 [  26.    0.  354.]]
('Epoch = ', 7)
('lr = ', 0.0001)
traintrain Loss: 0.0000262870 
Acc: 0.9999
[[  1.89700000e+03   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   3.31600000e+03   0.00000000e+00]
 [  0.00000000e+00   1.00000000e+00   3.01600000e+03]]
valval Loss: 0.0020358302 
Acc: 0.9781
[[ 265.    7.    0.]
 [  10.  381.    6.]
 [   0.    0.  380.]]
('Epoch = ', 8)
traintrain Loss: 0.0000265979 
Acc: 1.0000
[[ 1897.     0.     0.]
 [    0.  3316.     0.]
 [    0.     0.  3017.]]
valval Loss: 0.0022703497 
Acc: 0.9743
[[ 266.    6.    0.]
 [  10.  386.    1.]
 [  10.    0.  370.]]
('Epoch = ', 9)
traintrain Loss: 0.0000183969 
Acc: 1.0000
[[ 1897.     0.     0.]
 [    0.  3316.     0.]
 [    

valval Loss: 0.0058883991 
Acc: 0.9289
[[ 231.    1.    0.]
 [  23.  458.    0.]
 [   0.   53.  317.]]
('Epoch = ', 17)
traintrain Loss: 0.0000184962 
Acc: 1.0000
[[ 1978.     0.     0.]
 [    0.  3240.     0.]
 [    0.     0.  2986.]]
valval Loss: 0.0057387993 
Acc: 0.9307
[[ 232.    0.    0.]
 [  21.  460.    0.]
 [   1.   53.  316.]]
('Epoch = ', 18)
traintrain Loss: 0.0000169116 
Acc: 1.0000
[[ 1978.     0.     0.]
 [    0.  3240.     0.]
 [    0.     0.  2986.]]
valval Loss: 0.0044820088 
Acc: 0.9344
[[ 231.    1.    0.]
 [  21.  460.    0.]
 [   0.   49.  321.]]
('Epoch = ', 19)
traintrain Loss: 0.0000158371 
Acc: 1.0000
[[ 1978.     0.     0.]
 [    0.  3240.     0.]
 [    0.     0.  2986.]]
valval Loss: 0.0056757135 
Acc: 0.9234
[[ 232.    0.    0.]
 [  29.  452.    0.]
 [   3.   51.  316.]]
0.94459833795
2
here
('test accuracy= ', 0.96761658031088082)
[[ 513.   19.    1.]
 [  22.  898.   11.]
 [   2.   20.  830.]]
here
{'test': 2335, 'train': 8066, 'val': 1202}
('Epoch = ', 0)

traintrain Loss: 0.0000217265 
Acc: 1.0000
[[ 1915.     0.     0.]
 [    0.  3176.     0.]
 [    0.     0.  2989.]]
valval Loss: 0.0017199250 
Acc: 0.9809
[[ 268.    0.    0.]
 [   0.  443.   22.]
 [   0.    0.  421.]]
('Epoch = ', 9)
traintrain Loss: 0.0000205244 
Acc: 1.0000
[[ 1915.     0.     0.]
 [    0.  3176.     0.]
 [    0.     0.  2989.]]
valval Loss: 0.0008956442 
Acc: 0.9905
[[ 268.    0.    0.]
 [   0.  454.   11.]
 [   0.    0.  421.]]
('Epoch = ', 10)
traintrain Loss: 0.0000289620 
Acc: 0.9999
[[  1.91400000e+03   0.00000000e+00   1.00000000e+00]
 [  0.00000000e+00   3.17600000e+03   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   2.98900000e+03]]
valval Loss: 0.0015255688 
Acc: 0.9809
[[ 268.    0.    0.]
 [   0.  443.   22.]
 [   0.    0.  421.]]
('Epoch = ', 11)
traintrain Loss: 0.0000157728 
Acc: 1.0000
[[ 1915.     0.     0.]
 [    0.  3176.     0.]
 [    0.     0.  2989.]]
valval Loss: 0.0007992430 
Acc: 0.9896
[[ 268.    0.    0.]
 [   0.  453.   12.]
 [   0